all_stock_names =  [
"AAPL", "ACN", "ADBE", "AMD", "AKAM", "ANSS", "ADSK",
"ADP", "AVGO", "CDNS", "CSCO", "CTSH", "GLW", "DXC",
"FFIV", "FIS", "IT", "GOOGL", "GOOG",
"HPQ", "IBM", "INTU", "IPGP", "JNPR", "KLAC", "LRCX",
"MA", "MSFT", "MSI", "NTAP", "NFLX", "NVDA", "ORCL",
"PAYX", "PYPL", "QCOM", "CRM", "NOW", "SWKS", "SNPS",
"TTWO", "TXN", "V", "WDC", "ABT", "ABBV", "A", "AMGN",
"BAX", "BDX", "BIIB", "BSX", "BMY", "CAH",
"CI", "COO", "CVS", "DHR", "DVA", "XRAY",
"REGN", "HCA", "HSIC", "IDXX", "ILMN", "INCY", "ISRG",
"JNJ", "LH", "LL", "MDT", "MRK", "MT",
"PRGO", "PFE", "DGX", "RMD", "SYK", "TMO", "UNH",
"VRTX", "WAT", "ALL", "AXP", "AIG", "AMP", "AON", "AJG", "AIZ",
"BAC", "BK", "BLK", "HRB", "SCHW", "CB",
"CINF", "C", "CFG", "CME", "CMA", "DFS",
"FITB", "BEN", "GS", "HIG", "ICE", "IVZ",
"JPM", "KEY", "LNC", "MCO", "MMC", "MET",
"MS", "NTRS", "PNC", "PFG", "PGR", "PRU",
"RJF", "RF", "SPGI", "STT", "SYF",
"TROW", "USB", "UNM", "WFC", "ZION", "AAP", "AMZN", "AZO", "BBY", "CMG", "DHI",
"DRI", "DLTR", "EBAY", "EXPE", "F", "GPS", "GRMN",
"GM", "HAS", "HD", "HBI", "IPG", "KSS",
"LEG", "LEN", "LOW", "M", "MAR", "MAT", "MCD", "MGM",
"NKE", "ORLY", "PHM", "RL", "ROST", "SBUX", "SNA",
"TGT", "TJX", "TSCO", "ULTA", "VFC", "WHR", "YUM", "ADM", "CLX", "CAG", "CPB", "CHD", "KO", "CL",
"COST", "COTY", "EL", "GIS", "HRL", "SJM", "K", "KMB",
"KHC", "KR", "MKC", "TAP", "MDLZ", "MNST", "PEP",
"PG", "PM",  "SJM", "SYY", "TSN", "WBA", "WMT", "APA", "CVX",
"COP", "DVN", "EOG", "EQT", "XOM", "HAL", "HES",
"KMI", "MRO", "MPC", "NOV", "OXY", "OKE",
"PSX", "PXD", "SLB", "FTI", "VLO", "WMB", "AAL", "ALK", "ALLE", "BA", "CAT",
"CMI", "CSX", "CMI", "DE", "DAL","DOV", "ETN", "EMR",
"EFX", "EXPD", "FAST", "FDX", "FLR", "GD","GE",
"GWW", "HON", "IEX", "ITW", "JCI", "LMT", "MAS", "MMM",
"NSC", "NOC", "PCAR", "PNR", "PH", "ROK", "ROP",
"LUV", "SRCL", "TXT", "UNP", "VMC", "WAB", "APD", "AVY", "CF", "DD", "ECL", "FCX",
"IP", "LYB", "MOS", "NEM", "NUE", "PKG", "PPG",
"SEE", "SHW", "VMC", "WRK", "AEE", "AEP", "AES",
"AWK", "CNP", "CMS", "D", "DTE", "DUK", "ED", "EIX",
"ES", "EXC", "FE", "NEE", "NI", "PCG", "PNW", "PPL",
"SO", "SRE", "WEC", "XEL"
]
